[formatting]
allowed_blank_lines = 1

[[rule]]
keys = [
  "dependencies",
  "dev-dependencies",
  "build-dependencies",
  "toolchain",
  "workspace.dependencies",
]

[rule.formatting]
reorder_keys = true
