[workspace]
members = [
  "runtime_v8",
  "runtime_v9",
  "runtime_v10",
  "runtime_v11",
  "account_v8",
  "account_v9",
  "account_v10",
  "account_v11",
  "init_v8",
  "init_v9",
  "init_v10",
  "init_v11",
  "cron_v8",
  "cron_v9",
  "cron_v10",
  "cron_v11",
  "paych_v8",
  "paych_v9",
  "paych_v10",
  "paych_v11",
  "system_v8",
  "system_v9",
  "system_v10",
  "system_v11",
  "multisig_v8",
  "multisig_v9",
  "multisig_v10",
  "multisig_v11",
  "market_v8",
  "market_v9",
  "market_v10",
  "market_v11",
  "power_v8",
  "power_v9",
  "power_v10",
  "power_v11",
  "reward_v8",
  "reward_v9",
  "reward_v10",
  "reward_v11",
  "verifreg_v8",
  "verifreg_v9",
  "verifreg_v10",
  "verifreg_v11",
  "miner_v8",
  "miner_v9",
  "miner_v10",
  "miner_v11",
  "datacap_v10",
  "datacap_v11",
  "eam_v10",
  "eam_v11",
  "evm_v10",
  "evm_v11",
  "ethaccount_v10",
  "ethaccount_v11",
  "fil_actor_interface",
  "evm_shared_v10",
  "evm_shared_v11",
]
resolver = "2"

[workspace.dependencies]
ahash = "0.8"
anyhow = "1.0"
byteorder = "1.4.3"
cid = { version = "0.8", default-features = false, features = ["std"] }
frc42_dispatch = "3.0.0"
frc46_token = "3.1.0"
fvm = { version = "~2.3", default-features = false }
fvm_ipld_amt = { version = "0.5.1", features = ["go-interop"] }
fvm_ipld_bitfield = "0.5"
fvm_ipld_blockstore = "0.1"
fvm_ipld_encoding = "0.3"
fvm_ipld_hamt = "0.6.1"
fvm_shared = { version = "2", default-features = false }
fvm_shared3 = { package = "fvm_shared", version = "3.2", default-features = false }
getrandom = { version = "0.2.5" }
hex = "0.4.3"
hex-literal = "0.3.4"
indexmap = { version = "1.9", features = ["serde-1"] }
integer-encoding = { version = "3.0.3", default-features = false }
itertools = "0.10"
lazy_static = "1.4"
libipld-core = "0.14"
log = "0.4"
multihash = "0.16"
num = "0.4.0"
num-bigint = { version = "0.4.3", features = ["serde"] }
num-derive = "0.3"
num-traits = "0.2"
paste = "1.0.9"
quickcheck = "1"
quickcheck_macros = "1"
rand = "0.8"
regex = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1.8"
serde_tuple = "0.5"
serde_yaml = "0.9"
sha2 = "0.10.5"
thiserror = "1.0"
toml = "0.7"
uint = { version = "0.9.3", default-features = false }
unsigned-varint = "0.7.1"

fil_actors_runtime_v10 = { version = "1.0.0", path = "./runtime_v10" }
fil_actors_runtime_v11 = { path = "./runtime_v11" }
fil_actors_runtime_v8 = { version = "1.0.0", path = "./runtime_v8" }
fil_actors_runtime_v9 = { version = "1.0.0", path = "./runtime_v9" }
