[workspace]
members = [
  "runtime_v8",
  "runtime_v9",
  "runtime_v10",
  "account_v8",
  "account_v9",
  "account_v10",
  "init_v8",
  "init_v9",
  "init_v10",
  "cron_v8",
  "cron_v9",
  "cron_v10",
  "paych_v8",
  "system_v8",
  "system_v9",
  "system_v10",
  "multisig_v8",
  "multisig_v9",
  "multisig_v10",
  "market_v8",
  "market_v9",
  "market_v10",
  "power_v8",
  "reward_v8",
  "paych_v9",
  "paych_v10",
  "power_v9",
  "power_v10",
  "reward_v9",
  "reward_v10",
  "verifreg_v8",
  "verifreg_v9",
  "miner_v8",
  "miner_v9",
  "miner_v10",
  "verifreg_v10",
  "datacap_v10",
  "eam_v10",
  "evm_v10",
  "ethaccount_v10",
  "fil_actor_interface",
  "evm_v10/shared_v10",
]
resolver = "2"

[workspace.dependencies]
ahash = "0.8"
anyhow = "1.0"
blake2b_simd = "1.0"
cid = { version = "0.8", default-features = false, features = ["std"] }
frc42_dispatch = "3.0.0"
frc46_token = "3.1.0"
fvm = "~2.2"
fvm_ipld_amt = "0.5.1"
fvm_ipld_bitfield = "0.5"
fvm_ipld_blockstore = "0.1"
fvm_ipld_encoding = "0.2"
fvm_ipld_hamt = "0.6.1"
fvm_shared = "2.0"
hex = "0.4"
hex-literal = "0.3.4"
indexmap = { version = "1.9", features = ["serde-1"] }
integer-encoding = { version = "3.0.3", default-features = false }
itertools = "0.10"
lazy_static = "1.4"
libipld-core = "0.14"
libp2p-identity = { version = "0.1", default-features = false, features = [
  "peerid",
] }
log = "0.4"
multihash = "0.16"
num = "0.4.0"
num-derive = "0.3"
num-traits = "0.2"
paste = "1.0.9"
rand = "0.8"
regex = "1.6"
serde = "1.0"
serde_repr = "0.1.8"
serde_tuple = "0.5"
serde_yaml = "0.9"
sha2 = "0.10.5"
thiserror = "1.0"
uint = { version = "0.9.3", default-features = false }
unsigned-varint = "0.7.1"

fil_actors_runtime_v10 = { path = "./runtime_v10" }
fil_actors_runtime_v8 = { path = "./runtime_v8" }
fil_actors_runtime_v9 = { path = "./runtime_v9" }
