[package]
name = "fil_actors_evm_shared_v10"
description = "Shared libraries for the built-in EVM actor for Filecoin"
version = "10.0.0"
license = "MIT OR Apache-2.0"
authors = ["Protocol Labs", "Filecoin Core Devs"]
edition = "2021"
repository = "https://github.com/ChainSafe/fil-actor-states"
keywords = ["filecoin", "web3", "wasm", "evm"]

[dependencies]
serde = { workspace = true }
fvm_shared = { version = "3.0.0", default-features = false }
fil_actors_runtime_v10 = { workspace = true }
fvm_ipld_encoding = "0.3.3"
uint = { workspace = true }
hex = { workspace = true }
