[package]
name = "fil_actors_runtime_v10"
description = "System actors for the Filecoin protocol"
version = "10.0.0-alpha.1"
license = "MIT OR Apache-2.0"
authors = [
  "ChainSafe Systems <info@chainsafe.io>",
  "Protocol Labs",
  "Filecoin Core Devs",
]
edition = "2021"
repository = "https://github.com/filecoin-project/builtin-actors"

[dependencies]
anyhow = "1.0.65"
blake2b_simd = "1.0"
castaway = "0.2.2"
cid = { version = "0.8.3", default-features = false, features = [
  "serde-codec",
] }
fvm_ipld_amt = { version = "0.5.1", features = ["go-interop"] }
fvm_ipld_blockstore = "0.1.1"
fvm_ipld_encoding.workspace = true
fvm_ipld_hamt = "0.6.1"
fvm_shared = { workspace = true }
hex = { workspace = true, optional = true }
itertools = "0.10"
lazy_static = { version = "1.4.0", optional = true }
multihash = { version = "0.16.1", default-features = false }
num-bigint.workspace = true
num-derive.workspace = true
num-traits.workspace = true
paste = "1.0.9"
rand = "0.8.5"
regex = "1"
serde.workspace = true
serde_repr.workspace = true
sha2.workspace = true
thiserror = "1.0.30"
unsigned-varint = "0.7.1"

[dev-dependencies]
hex.workspace = true
quickcheck.workspace = true
quickcheck_macros.workspace = true
toml = "0.7"

[features]
test_utils = ["hex", "multihash/sha2", "lazy_static"]
