[package]
name = "fil_actor_miner_state"
description = "Builtin miner actor for Filecoin"
license.workspace = true
repository.workspace = true
authors.workspace = true
edition.workspace = true
version.workspace = true
keywords.workspace = true

[lib]
## lib is necessary for integration tests
## cdylib is necessary for Wasm build
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow = { workspace = true }
bitflags = { workspace = true }
cid = { workspace = true }
fil_actor_verifreg_state = { workspace = true }
fil_actors_shared = { workspace = true }
frc42_dispatch = { workspace = true }
frc42_macros = { workspace = true }
fvm_ipld_amt = { workspace = true }
fvm_ipld_bitfield = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_ipld_hamt = { workspace = true }
fvm_shared = { workspace = true }
fvm_shared3 = { workspace = true }
fvm_shared4 = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
multihash = { workspace = true }
num-bigint = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
unsigned-varint = { workspace = true }

[dev-dependencies]
fil_actors_test_utils.workspace = true
hex.workspace = true
pretty_assertions.workspace = true
quickcheck.workspace = true
quickcheck_macros.workspace = true
