[package]
name = "fil_actor_eam_state"
description = "Builtin Ethereum address manager actor for Filecoin"
license.workspace = true
repository.workspace = true
authors.workspace = true
edition.workspace = true
version.workspace = true
keywords.workspace = true

[dependencies]
fvm_shared3 = { workspace = true }
fvm_shared4 = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
