[package]
name = "fil_actor_evm_state"
description = "Builtin EVM actor for Filecoin"
license.workspace = true
repository.workspace = true
authors.workspace = true
edition.workspace = true
version.workspace = true
keywords.workspace = true

[dependencies]
cid = { workspace = true }
fil_actors_shared = { workspace = true }
frc42_macros = { workspace = true }
frc42_dispatch = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_shared3 = { workspace = true }
fvm_shared4 = { workspace = true }
hex = { workspace = true }
hex-literal = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
uint = { workspace = true }
