[package]
name = "fil_actor_init_state"
description = "Builtin init actor for Filecoin"
version = "4.0.0"
license = "MIT OR Apache-2.0"
authors = [
  "ChainSafe Systems <info@chainsafe.io>",
  "Protocol Labs",
  "Filecoin Core Devs",
]
edition = "2021"
repository = "https://github.com/ChainSafe/fil-actor-states"
keywords = ["filecoin", "web3", "wasm"]

[dependencies]
anyhow = { workspace = true }
cid = { workspace = true }
fil_actors_shared = { version = "4.0.0", path = "../../fil_actors_shared" }
frc42_dispatch = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_ipld_hamt = { workspace = true }
fvm_shared = { workspace = true }
fvm_shared3 = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true, features = ["derive"] }

# Dependencies only for Init V0 actor
address = { package = "forest_address", version = "0.3" }
encoding = { package = "forest_encoding", version = "0.2.1" }
fil_types = "0.2"
forest_cid = { version = "0.3", features = ["cbor"] }
ipld_blockstore = "0.1"
ipld_hamt = { version = "0.1", features = ["go-interop"] }
runtime = { package = "forest_runtime", version = "0.2" }
vm = { package = "forest_vm", version = "0.3" }
