[package]
name = "fil_actor_interface"
description = "Backward compatibility layer for all versions of builtin actor released v8 onwards."
license = "MIT OR Apache-2.0"
repository = "https://github.com/ChainSafe/fil-actor-states"
version = "2.0.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2021"

[dependencies]
fil_actor_account_v10 = { version = "2.0.0", path = "../account_v10" }
fil_actor_account_v11 = { version = "2.0.0", path = "../account_v11" }
fil_actor_account_v8 = { version = "2.0.0", path = "../account_v8" }
fil_actor_account_v9 = { version = "2.0.0", path = "../account_v9" }
fil_actor_cron_v10 = { version = "2.0.0", path = "../cron_v10" }
fil_actor_cron_v11 = { version = "2.0.0", path = "../cron_v11" }
fil_actor_cron_v8 = { version = "2.0.0", path = "../cron_v8" }
fil_actor_cron_v9 = { version = "2.0.0", path = "../cron_v9" }
fil_actor_datacap_v10 = { version = "2.0.0", path = "../datacap_v10" }
fil_actor_datacap_v11 = { version = "2.0.0", path = "../datacap_v11" }
fil_actor_evm_v10 = { version = "2.0.0", path = "../evm_v10" }
fil_actor_evm_v11 = { version = "2.0.0", path = "../evm_v11" }
fil_actor_init_v10 = { version = "2.0.0", path = "../init_v10" }
fil_actor_init_v11 = { version = "2.0.0", path = "../init_v11" }
fil_actor_init_v8 = { version = "2.0.0", path = "../init_v8" }
fil_actor_init_v9 = { version = "2.0.0", path = "../init_v9" }
fil_actor_market_v10 = { version = "2.0.0", path = "../market_v10" }
fil_actor_market_v11 = { version = "2.0.0", path = "../market_v11" }
fil_actor_market_v8 = { version = "2.0.0", path = "../market_v8" }
fil_actor_market_v9 = { version = "2.0.0", path = "../market_v9" }
fil_actor_miner_v10 = { version = "2.0.0", path = "../miner_v10" }
fil_actor_miner_v11 = { version = "2.0.0", path = "../miner_v11" }
fil_actor_miner_v8 = { version = "2.0.0", path = "../miner_v8" }
fil_actor_miner_v9 = { version = "2.0.0", path = "../miner_v9" }
fil_actor_multisig_v10 = { version = "2.0.0", path = "../multisig_v10" }
fil_actor_multisig_v11 = { version = "2.0.0", path = "../multisig_v11" }
fil_actor_multisig_v8 = { version = "2.0.0", path = "../multisig_v8" }
fil_actor_multisig_v9 = { version = "2.0.0", path = "../multisig_v9" }
fil_actor_power_v10 = { version = "2.0.0", path = "../power_v10" }
fil_actor_power_v11 = { version = "2.0.0", path = "../power_v11" }
fil_actor_power_v8 = { version = "2.0.0", path = "../power_v8" }
fil_actor_power_v9 = { version = "2.0.0", path = "../power_v9" }
fil_actor_reward_v10 = { version = "2.0.0", path = "../reward_v10" }
fil_actor_reward_v11 = { version = "2.0.0", path = "../reward_v11" }
fil_actor_reward_v8 = { version = "2.0.0", path = "../reward_v8" }
fil_actor_reward_v9 = { version = "2.0.0", path = "../reward_v9" }
fil_actor_system_v10 = { version = "2.0.0", path = "../system_v10" }
fil_actor_system_v11 = { version = "2.0.0", path = "../system_v11" }
fil_actor_system_v8 = { version = "2.0.0", path = "../system_v8" }
fil_actor_system_v9 = { version = "2.0.0", path = "../system_v9" }
fil_actors_runtime_v10.workspace = true
fil_actors_runtime_v11.workspace = true
fil_actors_runtime_v9.workspace = true

anyhow.workspace = true
cid.workspace = true
fvm_ipld_bitfield.workspace = true
fvm_ipld_blockstore.workspace = true
fvm_ipld_encoding.workspace = true
fvm_shared = { workspace = true }
fvm_shared3 = { workspace = true }
lazy_static.workspace = true
num.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true

[build-dependencies]
anyhow.workspace = true
cid.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
