[package]
name = "fil_utils"
description = "Utility for Builtin actors"
version = "10.0.0-alpha.1"
license = "MIT OR Apache-2.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2018"

[dependencies]
fvm_shared = { workspace = true }
fvm_shared3 = { workspace = true }
