name: "Publish Crate Action"
description: "Checks out the repository, sets up sccache, publishes a crate, and clears artifacts."
inputs:
  crate:
    description: "The crate to publish"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.5
      continue-on-error: true
    - name: Publish crate
      run: cargo publish --package ${{ inputs.crate }} --token ${{ env.CRATES_IO_TOKEN }}
      shell: bash
    - name: Clear artifacts
      run: cargo clean
      shell: bash
