[package]
name = "fil_actor_evm_v11"
description = "Builtin EVM actor for Filecoin"
version = "2.0.0"
license = "MIT OR Apache-2.0"
authors = ["Protocol Labs", "Filecoin Core Devs"]
edition = "2021"
repository = "https://github.com/ChainSafe/fil-actor-states"
keywords = ["filecoin", "web3", "wasm", "evm"]

[dependencies]
cid = { workspace = true }
fil_actor_evm_shared_v11 = { version = "2.0.0", path = "../../evm_shared/v11" }
frc42_dispatch = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_shared3 = { workspace = true }
hex-literal = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
