[package]
name = "fil_actors_runtime_v8"
description = "System actors for the Filecoin protocol"
version = "8.0.0"
license = "MIT OR Apache-2.0"
authors = [
  "ChainSafe Systems <info@chainsafe.io>",
  "Protocol Labs",
  "Filecoin Core Devs",
]
edition = "2021"
repository = "https://github.com/ChainSafe/forest"

[dependencies]
anyhow = { workspace = true }
cid = { workspace = true, features = ["serde-codec"] }
fil_actors_runtime_v10 = { path = "../runtime_v10" }
fvm_ipld_amt = { workspace = true, features = ["go-interop"] }
fvm_ipld_blockstore = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_ipld_hamt = { workspace = true }
fvm_shared = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_repr = { workspace = true }
thiserror = { workspace = true }
unsigned-varint = { workspace = true }

[features]
default = []
