[package]
name = "fil_actor_market_state"
description = "Builtin market actor for Filecoin"
version = "4.0.0"
license = "MIT OR Apache-2.0"
authors = [
  "ChainSafe Systems <info@chainsafe.io>",
  "Protocol Labs",
  "Filecoin Core Devs",
]
edition = "2021"
repository = "https://github.com/ChainSafe/fil-actor-states"
keywords = ["filecoin", "web3", "wasm"]

[features]
arb = ["dep:quickcheck"]

[dependencies]
anyhow = { workspace = true }
cid = { workspace = true }
fil_actor_verifreg_state = { version = "4.0.0", path = "../verifreg" }
fil_actors_shared = { version = "4.0.0", path = "../../fil_actors_shared" }
frc42_dispatch = { workspace = true }
fvm_ipld_bitfield = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_ipld_hamt = { workspace = true }
fvm_shared = { workspace = true }
fvm_shared3 = { workspace = true }
libipld-core = { workspace = true }
num-bigint = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
quickcheck = { workspace = true, optional = true }
serde = { workspace = true }

[dev-dependencies]
fil_actors_test_utils.workspace = true
hex.workspace = true
lazy_static.workspace = true
parking_lot.workspace = true
pretty_assertions.workspace = true
quickcheck_macros.workspace = true
