[package]
name = "fil_actor_market_state"
description = "Builtin market actor for Filecoin"
license.workspace = true
repository.workspace = true
authors.workspace = true
edition.workspace = true
version.workspace = true
keywords.workspace = true

[features]
arb = ["dep:quickcheck"]

[dependencies]
anyhow = { workspace = true }
cid = { workspace = true }
fil_actor_verifreg_state = { workspace = true }
fil_actors_shared = { workspace = true }
frc42_dispatch = { workspace = true }
frc42_macros = { workspace = true }
fvm_ipld_bitfield = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_ipld_hamt = { workspace = true }
fvm_shared = { workspace = true }
fvm_shared3 = { workspace = true }
fvm_shared4 = { workspace = true }
lazy_static = { workspace = true }
libipld-core = { workspace = true }
num-bigint = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
quickcheck = { workspace = true, optional = true }
serde = { workspace = true }

[dev-dependencies]
fil_actors_test_utils.workspace = true
hex.workspace = true
pretty_assertions.workspace = true
quickcheck_macros.workspace = true
