name: Publish Crates

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  RUSTC_WRAPPER: "sccache"

jobs:
  publish-shared:
    runs-on: ubuntu-latest
    env:
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Publish shared crate
        uses: ./.github/composite-actions/publish-crate
        with:
          crate: "fil_actors_shared"

  publish-independent:
    runs-on: ubuntu-latest
    env:
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    strategy:
      matrix:
        crate: [
          "fil_actor_account_state",
          "fil_actor_cron_state",
          "fil_actor_eam_state",
          "fil_actor_ethaccount_state"
        ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Publish independent crate
        uses: ./.github/composite-actions/publish-crate
        with:
          crate: ${{ matrix.crate }}

  publish-dependent-on-shared:
    runs-on: ubuntu-latest
    needs: publish-shared
    env:
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    strategy:
      matrix:
        crate: [
          "fil_actor_datacap_state",
          "fil_actor_evm_state",
          "fil_actor_init_state",
          "fil_actor_multisig_state",
          "fil_actor_paych_state",
          "fil_actor_power_state",
          "fil_actor_system_state"
        ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Publish dependent crate
        uses: ./.github/composite-actions/publish-crate
        with:
          crate: ${{ matrix.crate }}

  publish-verifreg:
    runs-on: ubuntu-latest
    needs: publish-shared
    env:
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Publish verifreg crate
        uses: ./.github/composite-actions/publish-crate
        with:
          crate: "fil_actor_verifreg_state"

  publish-market-and-miner:
    runs-on: ubuntu-latest
    needs: publish-verifreg
    env:
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    strategy:
      matrix:
        crate: [
          "fil_actor_market_state",
          "fil_actor_miner_state"
        ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Publish market and miner crates
        uses: ./.github/composite-actions/publish-crate
        with:
          crate: ${{ matrix.crate }}

  publish-reward:
    runs-on: ubuntu-latest
    needs: publish-market-and-miner
    env:
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Publish reward crate
        uses: ./.github/composite-actions/publish-crate
        with:
          crate: "fil_actor_reward_state"

  publish-interface:
    runs-on: ubuntu-latest
    needs: [publish-independent, publish-dependent-on-shared, publish-reward]
    env:
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Publish interface crate
        uses: ./.github/composite-actions/publish-crate
        with:
          crate: "fil_actor_interface"
