name: Publish Crates

on:
  workflow_dispatch:
  push:
    tags:
      - v*
env:
  RUSTC_WRAPPER: "sccache"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.5
        timeout-minutes: 5
        continue-on-error: true
      - name: Publish crates
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: ./scripts/publish.sh --token "$CRATES_IO_TOKEN"
