name: Tests

# Cancel workflow if there is a new change to the branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  workflow_dispatch:
  merge_group:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  # https://github.com/BurntSushi/quickcheck/blob/master/src/tester.rs#L21
  QUICKCHECK_TESTS: 10
  QUICKCHECK_MAX_TESTS: 100
  CC: sccache clang
  CXX: sccache clang++
  # To minimize compile times: https://nnethercote.github.io/perf-book/build-configuration.html#minimizing-compile-times
  RUSTFLAGS: "-C linker=clang -C link-arg=-fuse-ld=lld"


jobs:
  test:
    name: build-and-test
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9
        timeout-minutes: 5
        continue-on-error: true
      - uses: jdx/mise-action@v3
      - run: mise check-crates --validate-actor-version
      - name: Build
        run: mise build --validate-actor-version
      - name: Run tests
        run: mise test

  forest-sync-check:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'Release') }}
    name: forest calibnet sync check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9
        timeout-minutes: 5
        continue-on-error: true
      - uses: jdx/mise-action@v3
      - name: Update submodule forest
        run: mise update-submodules
      - name: Modify deps forest
        run: mise modify-forest
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Test forest
        working-directory: forest
        run: mise test
      - name: Install forest
        working-directory: forest
        run: mise run install
      - name: Calibnet health check
        working-directory: forest
        run: ./scripts/tests/calibnet_other_check.sh

  lint-all:
    name: All lint checks
    runs-on: ubuntu-24.04 # can't use arm64 due to dependency issues with udeps running on nightly
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v6
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9
        timeout-minutes: 5
        continue-on-error: true
      - name: Apt Dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          command: |
            sudo apt-get install -y libclang-dev # required dep for cargo-spellcheck
      - uses: jdx/mise-action@v3
      - name: Install Lint tools
        run: mise install-lint-tools
        env:
          # Should deal with rate limits
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mise run "lint:*"
