name: Tests

# Cancel workflow if there is a new change to the branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

on:
  workflow_dispatch:
  merge_group:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  # https://github.com/BurntSushi/quickcheck/blob/master/src/tester.rs#L21
  QUICKCHECK_TESTS: 10
  QUICKCHECK_MAX_TESTS: 100

jobs:
  test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9
        timeout-minutes: 5
        continue-on-error: true
      - uses: actions/setup-go@v5
        with:
          go-version-file: "./go_compat/go.mod"
      - run: make check
        env:
          CC: "sccache clang"
          CXX: "sccache clang++"
      - name: Build
        run: cargo check --workspace --all-features --all-targets
        env:
          CC: "sccache clang"
          CXX: "sccache clang++"
      - name: Run tests
        run: RUST_MIN_STACK=8388608 cargo test --workspace --all-features --all-targets
        env:
          CC: "sccache clang"
          CXX: "sccache clang++"

  forest-sync-check:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'Release') }}
    name: forest calibnet sync check
    runs-on: buildjet-8vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9
        timeout-minutes: 5
        continue-on-error: true
      - name: Update submodule forest
        run: make update-forest
      - name: Modify deps forest
        run: make modify-forest
      - uses: actions/setup-go@v5
        with:
          go-version-file: "./forest/go.work"
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Test forest
        run: |
          cd forest
          make test
        env:
          CC: "sccache clang"
          CXX: "sccache clang++"
      - name: Install forest
        run: |
          cd forest
          make install
        env:
          CC: "sccache clang"
          CXX: "sccache clang++"
      - name: Calibnet health check
        run: |
          cd forest
          ./scripts/tests/calibnet_other_check.sh

  lint-all:
    name: All lint checks (lint audit spellcheck udeps)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9
        timeout-minutes: 5
        continue-on-error: true
      - name: Install Lint tools
        run: make install-lint-tools
        env:
          RUSTFLAGS: "-Cstrip=symbols"
          # Should deal with rate limits
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: make lint-all
        env:
          CC: "sccache clang"
          CXX: "sccache clang++"

  cargo-dependency-check:
    name: Check cargo files for duplicates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
      - name: Run rubocop
        run: |
          gem install rubocop -v 1.57 --no-document
          rubocop scripts/
      - name: Run dependencies checks
        run: |
          gem install toml-rb --no-document
          ruby scripts/find_duplicate_deps.rb && \
          ruby scripts/find_unused_deps.rb --ignore serde --ignore num --ignore num-bigint --ignore num-traits --ignore fvm_ipld_bitfield
